#!/usr/bin/env python

import os, sys, re

from gwutils import *
from xwhen import *

COMMANDS = ['add', 'rm', 'msg']

def showHelp():
    print "USAGE:"

def parseArgs(argv):
    if len(argv) < 1:
        raise ParseError("Needs at least one argument")

    cmd = argv[0].lower()

    if cmd not in COMMANDS:
        raise ParseError("'%s': Invalid command" % cmd)

    if cmd in ['add', 'rm']:
        argv = argv[1:]
        if len(argv) != 1:
            raise FormatError("Format: gitwhen %s <filename>" % cmd)

        if cmd == 'add':
            return AddWhen(argv[0])
        elif cmd == 'rm':
            return RemoveWhen(argv[0])

    if cmd in ['msg']:
        argv = argv[1:]
        if len(argv) < 1:
            raise FormatError("Format: gitwhen %s <msg>" % cmd)
        
        if cmd == 'msg':
            return MsgWhen(' '.join(argv).strip())

try:
    xwhen = parseArgs(sys.argv[1:])
    xwhen.run()
    sys.exit(0)
except ParseError, e:
    print "gitwhen: %s" % e.args[0]
    showHelp()
except FormatError, e:
    print "gitwhen: %s" % e.args[0]

sys.exit(1)

