#!/usr/bin/env python

import os, sys, re

from gwutils import *

COMMANDS = ['add', 'rm']

class AddWhen:
    def __init__(self, filename):
        self.filename = filename

    def do(self):
        res = runCmd("git log --diff-filter=A -- %s" % self.filename)
        print res[0]
        #print res[1]

class RemoveWhen:
    def __init__(self, filename):
        self.filename = filename

    def do(self):
        res = runCmd("git log --diff-filter=D -- %s" % self.filename)
        print res[0]
        #print res[1]

def showHelp():
    print "USAGE:"

def parseArgs(argv):
    if len(argv) < 1:
        raise ParseError("Needs at least one argument")

    cmd = argv[0].lower()

    if cmd not in COMMANDS:
        raise ParseError("'%s': Invalid command" % cmd)

    if cmd in ['add', 'rm']:
        argv = argv[1:]
        if len(argv) != 1:
            raise FormatError("Format: gitwhen %s <filename>" %cmd)

        if cmd == 'add':
            return AddWhen(argv[0])
        elif cmd == 'rm':
            return RemoveWhen(argv[0])

try:
    worker = parseArgs(sys.argv[1:])
    worker.do()
    sys.exit(0)
except ParseError, e:
    print "gitwhen: %s" % e.args[0]
    showHelp()
except FormatError, e:
    print "gitwhen: %s" % e.args[0]

sys.exit(1)

